### ISSUE TITLE
Origin header manipulation can't be stopped?

### ISSUE THREAD

**Issue by irsdl** [PortSwigger/param-miner#48]
What setting should be used to stop param miner messing with the Origin header when guessing GET or POST parameters?
I have used the following settings but it still changes the Origin header which breaks my test (API does not work without the right Origin header):
![image](https://user-images.githubusercontent.com/1798313/105771528-95ce0600-5f58-11eb-8f6c-25b5afe3560b.png)

**Comment by albinowax** [comment]
I can't replicate this, maybe the cache-buster is coming from elsewhere?

**Comment by alonek1** [comment]
I have same problem,
It seems Origin is set by paramminer .
when i stop the paramminer the request sent without problem.(server checks the origin against CORS)

**Comment by albinowax** [comment]
Which version of Param Miner are you using? Can you show me an example request in the Logger?

**Comment by inhibitor181** [comment]
Ok, so this is caused by the `include origin in cachebusters` option. Be default it's checked. Removing the check fix this issue.

**Comment by nevkel** [comment]
Hi. I am also experiencing the behavior described above when using param miner with Burp Pro v2023.5.4. I have all other extensions disabled; only param miner enabled (Using albinowaxUtils v1.03; Loaded Param Miner v1.4f). I am attempting to guess GET query params. Each guess request has an Origin request header added by param miner with a random domain value, different for each request/guess attempt .e.g. Origin: https://nx60mb85.com). However, because the target implements CORS it just returns a 403 Forbidden with 'Invalid CORS request' as the body for each response. Is there a way to stop the injection of Origin request headers by param miner?

**Comment by albinowax** [comment]
Thanks for the report @nevkel . Can you provide a screenshot of your param miner settings?

**Comment by nevkel** [comment]
Hi James,

 

I've attached a screenshot of my param miner settings. Almost all is default, just threads and canary changed.

 

As a workaround, I simply fired up another instance of Burp Pro as an upstream proxy and used the Proxy match & replace with a regex to swap out the random domain names injected in the Origin: request header for a legit domain name. Then I found 10 previously unknown query string params ;-) 

Sweet as!

 

 

Have a nice day!

 

neville

 

 

 

 

 

 

 

 

 
 

Sent: Wednesday, June 28, 2023 at 4:42 PM

**Comment by albinowax** [comment]
Thanks, I'll take a look when I do my next push on Param Miner

**Comment by nevkel** [comment]
This Origin header scenario came up for me today again when using param miner. I stopped it (oh yeah, param miner needs a convenient stop button, please), unticked 'include origin in cachebusters:' and ran it again, and hey presto - worked a treat.
